services:

  nginx:
    image: $NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    volumes:
     - ./:/var/www/html/
     - ./_docker/nginx:/etc/nginx/conf.d/
    ports:
     - "80:80"

  php:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
     - ./:/var/www/html/
    container_name: "${PROJECT_NAME}_php"
    environment:
         PHP_XDEBUG: 1
         PHP_XDEBUG_MODE: profile,coverage,debug
         PHP_IDE_CONFIG: serverName=my-ide
         PHP_XDEBUG_IDEKEY: my-ide
         PHP_XDEBUG_START_WITH_REQUEST: trigger
         PHP_XDEBUG_TRIGGER_VALUE: my-ide
         PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
         PHP_XDEBUG_PROFILER_OUTPUT_NAME: "%t"
         PHP_XDEBUG_LOG_LEVEL: 0
    depends_on:
      - db

  db:
    image: $MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    volumes:
      - ./database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        MYSQL_DATABASE: $DB_NAME
        MYSQL_USER: $DB_USER
        MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "${PROJECT_NAME}_phpmyadmin"
    ports:
      - 44444:80
    environment:
      - PMA_ARBITRARY=1
